### ISSUE TITLE
iOS13対応に伴うREADME修正

### ISSUE THREAD

**Issue by kobayashi-masaya** [NIFCLOUD-mbaas/SwiftRichPushApp#6]
READMEに変更が生じるであろう箇所
- [概要の対応 iOS version](https://github.com/vfa-namnk/SwiftRichPushApp/tree/upgrade_to_ncmb_swift_v1.0.0#%E6%A6%82%E8%A6%81)
- [動作環境](https://github.com/vfa-namnk/SwiftRichPushApp/tree/upgrade_to_ncmb_swift_v1.0.0#%E5%8B%95%E4%BD%9C%E7%92%B0%E5%A2%83)
- [PushNotificationのONの仕方が変更になっている](https://github.com/vfa-namnk/SwiftRichPushApp/tree/upgrade_to_ncmb_swift_v1.0.0#5-%E5%AE%9F%E6%A9%9F%E3%83%93%E3%83%AB%E3%83%89)
- [画像のドメインがmb.niftyのまま](https://github.com/vfa-namnk/SwiftRichPushApp/tree/upgrade_to_ncmb_swift_v1.0.0#7%E3%83%AA%E3%83%83%E3%83%81%E3%83%97%E3%83%83%E3%82%B7%E3%83%A5%E3%82%92%E9%80%81%E3%81%A3%E3%81%A6webview%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%95%E3%81%9B%E3%81%BE%E3%81%97%E3%82%87%E3%81%86)
- [コードが赤くハイライトされている](https://github.com/vfa-namnk/SwiftRichPushApp/tree/upgrade_to_ncmb_swift_v1.0.0#ios9%E4%BB%A5%E4%B8%8A%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8Bhttp%E9%80%9A%E4%BF%A1%E8%A8%AD%E5%AE%9A)

**Comment by natsumo** [comment]
@kobayashi-masaya issue登録ありがとうございます。
動作環境のところ、掲載するにあたり動作確認いただいた環境を教えていただけますか？

**Comment by kobayashi-masaya** [comment]
動作環境は以下の通りです。
```
検証済み動作環境
Mac OS Mojave 10.14.4
Xcode ver.11.2 (11B52)
iPhone 8  iOS 13.3
```
ご確認お願い致します。
